### ISSUE TITLE
Permissions/Flag issues

### ISSUE THREAD

**Issue by ApexFlowers** [JimiIT92/UniverseGuard2#106]
I am having trouble getting the regions set up. I am not sure if its a problem with another plugin interfering, however in my spawn region they are not allowed to do anything at all. They cant access their inventory, they cant use any portals, they even get an error when they press spacebar to jump. After looking through the wiki, I could not find which flag controlled those settings.

On a side note, running /rg edit DIM-1 to edit the nether dimension returns an error of no value. I have yet to try this with any other of the regions besides text only ones like world and spawn.

/rg flag mobspawn all false also returns the error of no value. you can work around it by using /rg flag mobspawn allhostile and allpassive

*update*
my "spawn" region is the issue. I am not sure which flags are causing the issues stated above. I looked at everything on the wiki and was unable to find commands or permissions retaining to these events

**Comment by ApexFlowers** [comment]
update on /rg flaghelp for the other issue I was reading about, /rg flaghelp does not work but /rg help gives you flag help options

**Comment by JimiIT92** [comment]
Yes, as you find out there no flags, currently, that prevents players from jumping or open inventory (but now I'm thinking that could be useful in some cases). Anyway, the fact that it seems that you don't have the nether region is really strange. You could force it to generate using the `/rg globalfor` command, but as I said is strange since the plugin should automatically generate missing global regions on startup (note that this only works if Sponge recognize the dimension as a world, infact the globalfor command is for modded dimensions that sometimes aren't recognized correctly by Sponge itself). Also, the default Minecraft Spawn protection looks like have a higher priority, and has caused some issues in the past. Let me know if you can find anything, because there could also be some bugs in the plugin itself. Meanwhile feel free to send me the spawn region file if you want, so I can check if there is anything wrong in it

**Comment by ApexFlowers** [comment]
the nether region is generated, I just cant select it to edit it with. It shows up on my /rg list however when i type /rg edit DIM-1 it doesn't returns the no value. In the config files I was able to edit the region, however ive been unable to test if the changes actually worked. I can give you an update on that soon. 

My biggest issue I need to figure out is the portals. Is there any way to allow users to interact with the portals? it returns they dont have permission when trying to step through them. they are the basic portals for Direwolf20, The Nether, The Twilight Forest, the End, etc.

**Comment by JimiIT92** [comment]
I've tried in a test server, but unfortunately I can't find any issue, both with the inventory problems and the DIM-1, I can edit it as well using your Region files. So it has to be something related to the permissions plugin, that somehow goes in conflict with the plugin appearently (although this shouldn't be possible, since UniverseGuard should handle different things from Luckperms and Nucleus). By the way local regions are always prioritized over global regions, so you don't need to set the priority if is the only local region in the area. Unfortunately at this point the only thing I can suggest you to do is to either let the plugin recreate the regions, which I doubt should change anything, or try to contact the Luckperms or the Nucleus author, so they can also see if there is something conflicting and hopefully notify me

**Comment by ApexFlowers** [comment]
Thank you for looking into it! I will let you know what the other authors say. I am going to go ahead and close the issue for now.
