### ISSUE TITLE
Total Economy and Universe Guard 2

### ISSUE THREAD

**Issue by Harchvertelol** [JimiIT92/UniverseGuard2#107]
Is there any integration of this plugin with the plugin for the economy? To create regions for money? For example, 40 to 40 is free, and if the region expands beyond this, depending on the size by which it grows, pay money?

**Comment by JimiIT92** [comment]
This would be an interesting addon, but right now it isn't possibile since the plugin doesn't expose any event that you can catch and do your stuff. However, version 3 WILL HAVE these events. I'm creating this version specifically to be expandend and consumed by other plugins, so doing something like this will be easy, because you will be able to catch the event that got fired when a region expands and do your own implementation, even cancel the event completely if your checks fails. But unfortunately V3 is still in development, so you could wait for it to be ready. If you still can't wait you could also fork the repo and edit the RegionExpandExecutor class to your needs :)

**Comment by Harchvertelol** [comment]
Thank you!
