### ISSUE TITLE
mod conflict

### ISSUE THREAD

**Issue by LoagnZEX** [JimiIT92/UniverseGuard2#110]
a mod conflict with Multi Mine, i don't know if this is the proper place to post this. noob git hub user here.
this mod will prevent region to protect block when you set it.
it's a mod in RLCRAFT.

**Comment by JimiIT92** [comment]
Thank you for the report, I've seen that for some reason having that mod in a server completely overrides the destroy flag. Will fix that as soon as possible ;)

**Comment by JimiIT92** [comment]
Hi, sorry for the late response, I've been busy with my work and with version 3, which a first beta just for testing new commands will come out later this week :) Anyway, this should now be fixed in version 2.24, which can be found here :D
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.24
