### ISSUE TITLE
Cant add members to region

### ISSUE THREAD

**Issue by EragonRussia** [JimiIT92/UniverseGuard2#126]
![изображение](https://user-images.githubusercontent.com/68070406/92284398-8e0ab800-ef0a-11ea-9695-19726be93f11.png)
![изображение](https://user-images.githubusercontent.com/68070406/92284424-995de380-ef0a-11ea-85e2-c380f441d0e0.png)

**Comment by JimiIT92** [comment]
Looks like the Region you are trying to add a member doesn't have an owner. Is that the case?

**Comment by EragonRussia** [comment]
Yes, but /add owner causes the same issue.05.09.2020, 16:03, "JimiIT92" <notifications@github.com>:
Looks like the Region you are trying to add a member doesn't have an owner. Is that the case?

**Comment by JimiIT92** [comment]
Unfortunately I was unable to reproduce the issue 😕 However I've seen there were some inconsistency on the **/rg add** commands, most importantly some checks that were missing. Also note that the player to add to a Region must enter first the server at least once, that's because otherwise the plugin can't get its UUID from the username. I've just released a new version which has those missing checks, stating that is strange that you got the stacktrace in the first place (altough very useful)
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.26
