### ISSUE TITLE
[API 7] Certain mob spawns not working

### ISSUE THREAD

**Issue by tryolivier** [JimiIT92/UniverseGuard2#13]
Hello =)

I use the new universeguard2 you made (thanks !!)
it works good BUT i have a problem

we can't spawn animal like pig if i take a pig egg and do right clic i listen a sound like a pig spawn but the pig don't spawn, why ????

it's the same with chicken or cow ....

but wolf cat horse .... works

thanks to have a look

have a nice day

**Comment by JimiIT92** [comment]
Make sure the mobspawn flag is not set to false for those animals. I'll make some tests as soon as i can :)

**Comment by tryolivier** [comment]
I Never see mobspawn in flag.
Thats strange 

I have to look

May be add animalspawn to pig chicken. .. and mobspawn To creeper zombie. ....

Tanks ;)

**Comment by Brycey92** [comment]
#14

**Comment by JimiIT92** [comment]
That's because you don't have to look inside "flags" section. Is a bit tricky, the command to set if a mob should spawn or not is "/rg flag mobspawn <mobid> <value>". For instance, to disable creeper spawning you must type "/rg flag mobspawn creeper false". Then, when displaying the Region informations you'll see wich mobs are "handled" by the region under the mobs section, not the flags section. You should see it under the vehicles informations :) Also this gives me an idea too, the ability to set mobs categories with one command (like only-animals, all-hostiles and so on...). Please check if in the mobs section of your region the selected mob you don't want to spawn actually doesn't. If a mob you specify to not spawn is spawning then there is a bug to  fix :)

**Comment by tryolivier** [comment]
1st : i dont see mobspawn on list of flag : https://i.imgur.com/m0PA9Nm.png
2nd : I put to test /rg flag mobspawn chicken true and /rg save but chicken still don't spawn 

thanks

**Comment by JimiIT92** [comment]
That's because the mobspawn flag, like "explosiondestroy, explosiondamage, interact, vehicleplace, vehicledestroy, mobpve, mobdamage, mobdrops", should not be there, since it's not a "unique" flag. Is not a value that's true or false for everything, like the place flag for example, it's value can be different based on mob. That's why it has it's own section below in the region infos :) Apart from that i'll see why the flag doesn't work and see how to fix that for the next release ;)

**Comment by JimiIT92** [comment]
Version 2.7 released! :D 
https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/116
