### ISSUE TITLE
Flag in the global region

### ISSUE THREAD

**Issue by zmax101** [JimiIT92/UniverseGuard2#133]
Hello, chests are disabled in the global region. 
When you change the configuration file, nothing changes. The server rebooted after changing the file, players can't open chests

**Comment by zmax101** [comment]
Changes to the universeguard.conf file do not work.
Rebooted the server, reloaded the plugin

**Comment by IcyTitan** [comment]
> Changes to the universeguard.conf file do not work.
> Rebooted the server, reloaded the plugin
Hello! I took the following steps to solve the problem:
I do not know which of the points is exactly, it's too lazy to test. I placed the plugin in the root of the mods folder (not a subfolder in it) + updated sponge to spongeforge-1.12.2-2838-7.3.0
After all these manipulations, the plugin config worked. The problem was on spongeforge-1.12.2-7.1.0
