### ISSUE TITLE
The flag "Enter" disable the flag "Greeting"

### ISSUE THREAD

**Issue by DarkStar0790** [JimiIT92/UniverseGuard2#142]
If you make a region with  the Flag Greeting (/rg greeting example) will work good, each time you enter the region the greeting will appear.  But when you add the Flag Enter to the region and set the Flag Enter to false (/rg flag flag enter false) the greeting message will no longer appear.  Only will appear the /rg farewell. 
To solve this you need to set the Flag enter to true.

This should be resolve cause the greeting is very useful but also the enter in false.  Both should work together.

For now, what im thinking is to add 4 regions around the principal one.  each of this region will cover each side (left, right, front and back) and those 4 regions will have the flag enter in false.  so the principal one (the one that will be in the middle) will have the flag enter in true, so with this will make that the greeting flag in the principal one appear each time you enter and the 4 regions outside in each side will block people from entry.  Just that i will need to add the members owners of the region to the 5 regions (prinpical, and 4 outsides around).

Please fix it :(

**Comment by JimiIT92** [comment]
This behaviour is intentional, since if you can't enter a Region than there wouldn't be no sense to display a greeting message (since no one without permission will ever see it). However, from what I understand, you want that players must not exit the Region. If that is the case you can solve it by using the `exit` flag and set it to true. This way Players will enter the Region, and have the Greeting message, but they won't be able to leave (you essentially create a trap Region)
