### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by ObnoxiousZombi** [JimiIT92/UniverseGuard2#147]
Is there any way to set permissions for non admin players? I want my players to be able to make/change their own regions without fear of them touching the global regions or any important local regions. Sorry if this wasn't the right place for this question, and thanks.

**Comment by Vulant** [comment]
Since UG2 is a sponge plugin, I'm assuming you're using LuckPerms.

I know it's a little difficult to find, but there are generally two permissions with UG2.

> Sets the default permissions used by UniverseGuard. These permissions are:
> 
> all: every player with this permission will have unlimited access to the UniverseGuard's functionalities
> region: every player with this permission will be able to bypass Region restrictions, but some commands and features are restricted to him.

Since it may seem that you're looking for more specific control over perms, it may not be possible to achieve what you're looking for.

As a side note, Jim, I'd like to suggest adding more permission nodes for each feature of UG2 to allow better perm control for multiplayer servers.

**Comment by JimiIT92** [comment]
I know is becoming a meme now, but a proper permission system will be added in v3, where you will be able to define permissions for basically everything you can come in mind (you could also do so only certain players can bypass or be restricted by a flag in the same Region, for example). The problem is that v3 must be radically different from the current UniverseGuard, not only from a codebase perspective (which for v2 at this point is really old and becoming a mess). I think I'll make a pinned issue this week where I will explain in detail the state of v3 and why is it taking so long
