### ISSUE TITLE
Region Files were broken after update to 2.33

### ISSUE THREAD

**Issue by SidewinderDX** [JimiIT92/UniverseGuard2#152]
Hey, after the update to Version 2.33 my region files were broken. I previously converted them from the WorldGuard format to yours (I scripted a short python script for that purpose. 😄) and with the old 2.32 Version it worked just fine, during the update UniverseGuard also updated all the regions to match the actual version number of the plugin. In my case most of the region members got lost and had no more rights to open chests for e.g.
After a small "Update" of the versionnumber in the old region files everything kept fine.
Don't know if its a bug or just stupid me. :'D

**Comment by JimiIT92** [comment]
The first cause I can think of is that the plugin keep tracks of the regions inside the index.json file. Maybe when you converted regions from worldguard to universeguard you forgot to update the references inside the index.json file, so essentially the plugin assumed that these files were regions in the old format, and it converted to the new one (this process actually looses some infos about the region because in the old format they were completely different and misses some parts, therefore are not converted at all). I am still interesetd in this tool and to see it in action, so maybe I can figure out how to add support for that and add to the wiki an "official" way to do it :D

**Comment by SidewinderDX** [comment]
The references for the index were up to date before the update, I assume it was only the fact, that the version number was old and the plugin updated it to the matching one while also creating new IDs. But I have no clue why it lost the members on its was.

Her a link to my repo, not the nicest Code but mostly written after a long work day. :D
[https://github.com/SidewinderDX/WG-UG-Converter](url)
