### ISSUE TITLE
universeguard.conf not in its config folder

### ISSUE THREAD

**Issue by zipacna** [JimiIT92/UniverseGuard2#163]
Shouldn't the universeguard.conf be in the config folder with its name?

Sponge Vanilla universeguard-2.33 (tested on linux and windows)

**Comment by JimiIT92** [comment]
Short answer: yes, it should.
Long answer: when I wrote this plugin I decided, for whatever reason, to just leave the core config file in the root of the config folder, and the rest of configuration, like region files, in the plugin dedicated folder. As Sponge grown up and there are more plugins available now than few years back, having everything organized is essential, so I agree that everything related to a plugin should be in its own folder. However changing that now could potentially break a lot of servers where the plugin is installed, since people will need to copy the old file inside the folder (not a big deal imho, but you know...), otherwise the core settings will be read from the "new" file, and they might be different from what a user already set. That being said, v3 will have in general a more organized config structure, with different files for flag default values, language, and so on, and everything will be inside the plugin folder.
