### ISSUE TITLE
Players are unable to open chests in the world

### ISSUE THREAD

**Issue by Dente222** [JimiIT92/UniverseGuard2#171]
I have come across that my friend was unable to open chest that she placed, further investigation showed that for region "world"
chest flag was set to false by default, it would be nice if this flag could be set to true by default for every dimension.

Also I think its a bug but before she was able to open chest until she placed her own but chests that I have placed before she was also able to open so at some point I have no idea why she was able to open some but later not able... confusing tbh

**Comment by JimiIT92** [comment]
That is because in global regions chests are not affected by who actually placed them. If you want a particular chest to be protected you need to place it in a local region where only you have access. In the future you will be able to do something similar to how the "signs" works in some bukkit plugins using addons for UniverseGuard. The default value is false because in majority of servers you aren't able to open chests in common areas, like the lobby. If I change this to be true by default than every new region will have that set to true as well, meaning that a server moderator/admin will always need to set the flag to false, and this can lead to them forgetting about it and accidentally create regions where players can open chests while they shouldn't

**Comment by Dente222** [comment]
Hmm oki I understand
Can you tell me how priority works in your plugin? I have no idea if 0 is the highest or lowest priority and can't really find any info about that too :L also sorry for offtopic

**Comment by Alydus** [comment]
@Dente222 For me, a higher number created a higher priority in the region hierarchy when they overlap.

**Comment by JimiIT92** [comment]
Can confirm, the higher the value the higher the priority. 0 is also not the lowest, you can go negative as well, is just a standard value
