### ISSUE TITLE
Feature Request: Permission for /rg wand

### ISSUE THREAD

**Issue by DrprofLuigi** [JimiIT92/UniverseGuard2#20]
I used worldguard (as I'm sure many others have) to protect the server spawn. However, I don't want players to be able to protect their builds. A permission to restrict the use of /rg wand would be very helpful for this reason.

Thanks for making this much-needed sponge plugin, and I hope it continues. There hasn't been a good worldguard replacement since spigot.

Also, you should add a hostile mob spawn flag. It would make things a smidge more convenient :)
i.e. /rg flag mobspawn hostile false

**Comment by JimiIT92** [comment]
The region wand already have a permission restriction, since you get the item only via command and only if you have a specific permission. I can add a further control for permission when you actually use the wand, however that item shouldn't be given to players intentionally ;) 
As for the hostile mob spawn flag, it will be added in the next release :)

**Comment by DrprofLuigi** [comment]
Oh, coolio!

**Comment by eheimer** [comment]
Could maybe just add a perms check when the player tries to use the tool?  If you don't have permissions to /rg, then the tool doesn't do anything.

**Comment by JimiIT92** [comment]
Version 2.7 released! :D 
https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/116
