### ISSUE TITLE
Feature Request: Make it possible to use the server console instead of in-game commands

### ISSUE THREAD

**Issue by YorVeX** [JimiIT92/UniverseGuard2#21]
Since I plan to create lots of protection areas I'd like to script this in the server, which means executing console commands on the server. There are several problems that prevent me from doing so right now.

1) Commands that work in-game are not working on console, e.g. "rg list" or "region list" simply do nothing on console, while others say *No values matching pattern 'PlayerName' present for name!* although the same command works in-game.

2) Commands referring to users don't work when the user is currently not connected to the server. It always ends up with the message *No values matching pattern 'PlayerName' present for name!* (similar message as for 1. but it also happens in-game and works as soon as the player has connected).

3) There is no command that does what touching of a block with the Region Selector item is doing.

**Comment by JimiIT92** [comment]
Using commands in console is one of the feature that is planned for the next version, because even i would find that useful ;) As for the players not being found if he's offline the problem could be related to how the plugin tries to get the player. As far as i know the sponge api should get a player if he's offline but only if he joined at least once the server, but i'll look more in depth into this. As for the command that simulates the selector that will come with the console commands, as i plan to add a command to create a region giving coordinates, so i'll include this feature in the next release ;)

**Comment by YorVeX** [comment]
I definitely got the error for an offline player for someone who has been on the server before, so there must be something else going on. Although even if that was fixed I would rather have it work even for people who have never been connected.

Either way, thanks for your response, looking forward to get those new features. You're doing a really good job there!

**Comment by JimiIT92** [comment]
For players that has been in the server it should work, so there's a bug in there and i'll look into it. For people who never joined the server that's a bit complicated, because when you add a player to a Region it adds it's UUID, so if a player never joined the server essentially the server doesn't know his UUID. I can check if i can use the Mojang API to get a player from his username (and this will potentially fix the first problem too)

**Comment by YorVeX** [comment]
That should be possible, e.g. look [here](https://bukkit.org/threads/how-to-convert-uuid-to-name-and-name-to-uuid-uising-mojang-api.460828/).

**Comment by JimiIT92** [comment]
Thanks, i'll look into it ;)

**Comment by JimiIT92** [comment]
I've looked into the tutorial you posted above. Really interesting and useful, but unfortunately i can't add that into the plugin due to multiple reasons. The first one, wich is the main one, is listed in the tutorial's topic too: "What if somebody has a slow connection (IE mobile broadband or something) and the request takes 5 seconds? Then you'll freeze the entire server, and probably crash it in the process.". Testing locally, with just me in the server, i've notice it takes a second or two before getting some results, so imagine that in a bigger server, even with 4 or 5 users on the server it could be a problem. The second reason is that changing how players are retrieved by the command will break any player related thing. This is not a big problem, but it will end up loosing many features such as tab completition but also and most importantly the methods to get the player won't work and will leads to crashes :/ Therefore the best i can do about this is find a way to get a player that has been in the server at least once using the sponge api (i guess there is some sort of history of players who joined the servers like there is in bukkit)

**Comment by JimiIT92** [comment]
Added in version 2.8! Check the Sponge page soon to get more details about ;) 
https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661
