### ISSUE TITLE
/rg flag mobspawn doesn't work

### ISSUE THREAD

**Issue by QueenGambit** [JimiIT92/UniverseGuard2#24]
/rg flag mobspawn doesn't work. I tried /rg flag mobspawn false or /rg flag mobspawn any false or /rg flag mobspawn zombie false.

**Comment by JimiIT92** [comment]
Make sure you are editing a region before using this command (otherwise it won't work). Also you need to specify the id of the mob in order to get the command work. For example, for zombies you have to type /rg flag mobspawn minecraft:zombie false. I know this is not optimal and i'm working on a way to avoid doing this, but at the moment that's the only recognized syntax for specific mobs. If you want to block all mobs you have to type /rg flag mobspawn all false, not any as you tried ;)

**Comment by QueenGambit** [comment]
ah okay thank you @JimiIT92. It was not specified in the documentation both the example for zombie and all mobs.
