### ISSUE TITLE
What flag is needed or is it a mistake?

### ISSUE THREAD

**Issue by Artem-18** [JimiIT92/UniverseGuard2#26]
Hi! We create server on sponge with use of Your plugin what we need flag to we could kill negative (or any mobs)? I watched the flags on damage to mobs, but they are included (green), and Bob hand them does not work. Region by the way the building spawn, need to negative the mobs did not spawn in it and you can hit it. Thank You!

**Comment by JimiIT92** [comment]
From what i've understand you want a way to disable all hostile mobs from spawning but at the same time give the ability to damage them? If so than you can set the mobspawn to false for all hostile mobs using the "/rg flag mobspawn allhostile false" command and then enable the damage to all hostiles by using the "/rg flag mobpve allhostile true" command. Make sure you are editing the Region before using these commands (otherwise they won't work)

**Comment by Artem-18** [comment]
The error is exactly the same as on the screenshot, sorry that I saw it only once asked a question. In the regular world PVE does not work, waiting for edits. :)
![38372259-4b26f56c-38e6-11e8-9b10-5b8d4385ff02](https://user-images.githubusercontent.com/33006666/38778816-8f46f130-40d8-11e8-9995-a02a15575cf4.png)

**Comment by JimiIT92** [comment]
Aaaah, now i see what the problem is. Is realted to a bug with the mobspawn flag, essentially setting that flag to false sets all other properties to false (so pve, damage and drops). This has bneen fixed and will be out with the next release ;)
