### ISSUE TITLE
Feature Request: Poly Regions

### ISSUE THREAD

**Issue by Brojman** [JimiIT92/UniverseGuard2#32]
Would it be possible to have regions that are made up of more than 2 points? Worldguard had a feature like this and I built an adventure map that had poly regions with over 15000 points. I am trying to bring that map back online but no protection plugins have poly regions.

**Comment by JimiIT92** [comment]
That's because having a square region or a shape-based region is easier to program and is also what the majority of users will use the most. I agree that poly-regions will be a huge improvement but since it will be really hard to do it i'll remind this when there won't be some major problems to fix so i can focus totally on this ;)

**Comment by JimiIT92** [comment]
This feature will be added in the next major version (Version 3) wich is in development
