### ISSUE TITLE
Users do not have permissions for any /region commands unless granted all permissions.

### ISSUE THREAD

**Issue by seisatsu** [JimiIT92/UniverseGuard2#33]
I am using LuckPerms, and my users cannot use any /region subcommands. In the config, it appears that the only configurable permissions are "universeguard.all" and "universeguard.region", and obviously I don't want to give those permissions to regular users. There seems to be no mention of what permission will grant users the ability to use the region commands that are supposed to be available to everyone.

**Comment by JimiIT92** [comment]
That's because the original scope of the plugin was to provide server's administrators/moderators a tool to protect their areas, and not a tool to give the ability to players to make their own regions. But, as it seems to be largely requested, a proper permission system to allow this will be implemented, but as it won't be easy it will certainly take some time before it will comes out ;)

**Comment by JimiIT92** [comment]
A proper permission system will be added in the next major version (Version 3) wich is in development
