### ISSUE TITLE
UniverseGuard is not properly working with Chisels&Bits (Not registering events).

### ISSUE THREAD

**Issue by TeKGameR950** [JimiIT92/UniverseGuard2#39]
**I am currently running**
- SpongeForge version: 1.12.2-2655-7.1.0-BETA-3105
- Forge version: 14.23.3.2655
- Java version: JAVA 8

- Plugins/Mods:
**Plugins (12): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, FlexibleLogin, LuckPerms, Nucleus, PlaceholderAPI, SkinsRestorer, Total Economy, Universe Guard 2, VirtualChest**
**Mods (18): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Chisel, Chisels & Bits, CustomNPCs, Gliby's Voice Chat Mod, HyPlay Mod, Iron Chest, MalisisCore, MalisisDoors, MrCrayfish's Furniture Mod, Obfuscate, Vehicle Mod, WorldEdit**

**Issue Description**

This issue is divided in 2 parts:

1.- If you try to chisel a block inside a protected region (UniverseGuard, FoxGuard, SafeGuard, etc), you will get the drop but the block won't be modified.

2.- If the block inside a protected region IS ALREADY chiseled, you will be able to modify it and you will also get the drop.

Chisel and Bits source: https://github.com/AlgorithmX2/Chisels-and-Bits
As the source code is disponible i'm pretty sure you can add a flag for it.

Thanks for reading.

**Comment by JimiIT92** [comment]
I'll look into this issue but if the event is just a place event than i guess there's nothing much i can do as that flag is handled right now. Perhapaps, if that is the case, i'll consider adding a setting so that you can specify wich blocks can be placed regardless of the flag

**Comment by JimiIT92** [comment]
I've looked into this and the problem as i suspect was related to the place flag. Essentialy when you chisel a block the mod places it's own one, for example if you chisel a sandstone block the mod will place it's own chiseled sandstone block. But if that flag is set to false the block can't be placed and so you get the bug. The fix to this will be refactoring those flags to allow blocks to be excluded, so you can still have that flag to false but allow some blocks to be placed anyway. Because this will be a major change that will require many tests, i'll remind this for the next release after the upcoming one. So in version 2.11 there will be this feature to exclude blocks from these flags, so stay tuned for updates ;)

**Comment by TeKGameR950** [comment]
Okay, thanks really :D

**Comment by JimiIT92** [comment]
The ability to exclude some blocks from being handled by the place and the destroy flag has been added in version 2.12 for Minecraft 1.12.2 only. You can now exclude the chisel and bits blocks from being handled so players will still be able to edit blocks using this mod ;) More infos on the official sponge post [here](https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/158) :D
