### ISSUE TITLE
Prevent Use

### ISSUE THREAD

**Issue by sfxworks** [JimiIT92/UniverseGuard2#52]
Like would guard people still have the ability to grief a spawn by using launchers. Can you please make a item use flag like world guard had?

**Comment by JimiIT92** [comment]
Version 2.16 released! It has the ability to block some items using a new command, although the explosions related might not be catched because of the reasons written in the post ;)
[https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/177](https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/177)
