### ISSUE TITLE
The Scheduler tried to run the task Enter Flag Timer Task owned by Plugin{id=universeguard, name=Universe Guard 2

### ISSUE THREAD

**Issue by XclusivVv** [JimiIT92/UniverseGuard2#58]
Hello my console is being spammed with errors non-stop https://pastebin.com/DY7UQuUc

It happened when I was in the middle of creating a new region, and typed /rg add command into chat to add a member to a seperate region. Was this error caused/triggered by me editing 2 regions simultaneously?

How can I fix this issue, it spams the console whenever I restart the server.

Also could you please let me know if there are any known issues with Universe Guard 2 and GriefPrevention. It's becoming a nightmare having them both. Universeguard offers me a worldedit kind of approach to anti griefing but I have to setup everyones claim individually which is time consuming, where as GP allows a user to place a chest and it's already setup for them. Each have their own merits, I would like them to work side by side if possible.

Update: I checked the regions JSON file, and it had replaced the second part of the region with "null" in all the fields. I don't know if that information helps. I removed the JSON file for the region, and the error was gone.

**Comment by JimiIT92** [comment]
Sounds like a version upgrade problem, because of the null values in region files. Will fix that in the new version. As for the GriefPrevention compatibility i'ver never tested if there are any issues with it and none has ever reported, so i guess you can have both installed (by the way the chest thing from GriefPrevention is probably similar to the templates in UniverseGuard, where you define all rules for a region once and then it's just creating new regions starting from that template)
