### ISSUE TITLE
Is there a way to manually set the coordinates for a region?

### ISSUE THREAD

**Issue by guyman70718** [JimiIT92/UniverseGuard2#7]
I'm on 1.12.2 and all my old regions and commands work, except for the /rg command to get a wand. Is there a command that I can use to set the coordinates for the corners?

**Comment by JimiIT92** [comment]
1.12.2 is currently not supported because an API7 version of the plugin is still in development. Even if commands works this don't mean the plugin works, many events are even gone in API7 so the plugin will not work. Those said, giving the ability to specify region with this command formatting (so you can create regions even from the console) is in the "TO-DO" list and will be added in a future release (maybe just the API7 release ;) )

**Comment by JimiIT92** [comment]
Released API7 version for MC-1.12.2. Read more at [https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/87](https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/87)
