### ISSUE TITLE
How to divide by areas

### ISSUE THREAD

**Issue by Unaim1** [JimiIT92/UniverseGuard2#72]
Hi,
I have an area in my modded server, version 1.12.2

How can I protect all the area, and then divide by small areas to give players access to interact but not build/break nothing, and another areas to give them a small house for example.

Is it possible to create a BIG area to protect all the map, and then smallers one to give them a house for example, to the players?

**Comment by JimiIT92** [comment]
You should look at Global Regions. They will define a set of rules that are valid for the dimension they set in. Otherwise you can define a big region and then define smaller regions giving them a higher priority. Remember that if you have multiple regions in one location only the one with the highest priority will set the rules
