### ISSUE TITLE
A warning keeps getting spammed into the server's console.

### ISSUE THREAD

**Issue by Killingman107** [JimiIT92/UniverseGuard2#77]
Sponge Version: 1.12.2-2825-7.1.6
UG2 Version: 2.18

Issue: A warning keeps getting spammed into the server's console.

The Error: https://pastebin.com/raw/s4hLQ0PC

The error began happening after updating from UG2 v2.17 to v2.18. I've tried to delete all configuration files relating to UG2 and setting the world's flags as I had prior.

**Comment by JimiIT92** [comment]
Will look into this

**Comment by Killingman107** [comment]
> Will look into this

Alright, thanks a bunch for your hard work!

**Comment by JimiIT92** [comment]
I've just released version 2.19. I've seen wich part of the code could cause the issue, it was just a brackets issue, since i was unable to get that warning on my tests. Let me know if the spam still occurs ;) You can find the new version here
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.19
