### ISSUE TITLE
Region visualisation

### ISSUE THREAD

**Issue by AykaSova** [JimiIT92/UniverseGuard2#90]
Hi there!
Great job going really above WorldGuard! 
But missing a visialisation method for region — like worldeditcui selection. Should be some threasure if you'll implement something like /rg sel/desel<ect> or anyhow...

**Comment by JimiIT92** [comment]
Hi, region visualizer is something I'm trying to do since the version 1, but never found out a way to do it :/ Maybe version 3 (whenever I'll find some time to work on) will have this feature since it will expose some apis (and so sidemods could listen to ug events and do stuff, like visualizing things).
For the two commands can you explain what they should do (ironically I don't know/use world guard too much)
